personality = "pragmatic"
model = "gpt-5.3-codex"
ask_for_approval = "never"

[tools]
allow_all = true

[projects."/Users/josh/Projects/_archive/warehouse"]
trust_level = "trusted"

[projects."/Users/josh/Projects/work"]
trust_level = "trusted"

[projects."/Users/josh/Projects/_whaleen/video-tiling"]
trust_level = "trusted"

[projects."/Users/josh/Projects"]
trust_level = "trusted"

[projects."/Users/josh/Projects/_whaleen/tiles"]
trust_level = "trusted"

[projects."/Users/josh/Projects/_whaleen/nostr-solana"]
trust_level = "trusted"

[projects."/Users/josh/Projects/_nothingdao/earth"]
trust_level = "trusted"

[projects."/Users/josh"]
trust_level = "trusted"

[projects."/Users/josh/Projects/_whaleen/den"]
trust_level = "trusted"

[projects."/Users/josh/Projects/_whaleen/ephemeral"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.2-codex" = "gpt-5.3-codex"
