#!/usr/bin/env lua

-- Load the sketchybar Lua module
package.cpath = package.cpath
  .. ";/usr/local/lib/lua/5.4/?.so"
  .. ";/opt/homebrew/lib/lua/5.4/?.so"
  .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"

sbar = require("sketchybar")

sbar.begin_config()
require("bar")
require("default")
require("items")
sbar.end_config()

sbar.event_loop()
